# config/series.yml
series:
  math_of_ML:
    book_slug: math_of_ML
    post_to_instagram: true

  MAS:
    book_slug: MAS
    post_to_instagram: false

  mixed:
    book_slug: mixed
    post_to_instagram: false
    options:
      - math_of_ML
      - MAS
