name: build-linux-wheels
on:
  workflow_dispatch: {}

jobs:
  wheels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build/download manylinux wheels
        run: |
          set -e
          python -m pip install --upgrade pip wheel
          mkdir -p vendor/wheels
          # Download prebuilt manylinux wheels only
          pip download --only-binary=:all: --dest vendor/wheels \
            manim plotly vpython pycairo moderngl moderngl-window kaleido libcairo2 libpango-1.0-0 libpangocairo-1.0-0
          echo "== wheels =="
          ls -al vendor/wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: vendor-wheels-linux
          path: vendor/wheels/*.whl
