name: build-linux-wheels
on:
  workflow_dispatch: {}

jobs:
  wheels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build/download manylinux wheels
        run: |
          set -e
          python -m pip install --upgrade pip wheel
          mkdir -p vendor/wheels

          # Only Python packages that have manylinux wheels
          pip download --only-binary=:all: --dest vendor/wheels \
            "manim==0.19.0" \
            "plotly==5.24.1" \
            "kaleido==0.2.1" \
            "vpython==7.6.5" \
            "moderngl==5.12.0" \
            "moderngl-window==3.1.1"

          echo "== wheels =="
          ls -al vendor/wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: vendor-wheels-linux
          path: vendor/wheels/*.whl
