name: Test OpenAI Key
on:
  workflow_dispatch:

jobs:
  test-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show OpenAI key length (safe)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
          import os
          key = os.environ.get("OPENAI_API_KEY","")
          print(f"Key length: {len(key)}")
          PY
